### ISSUE TITLE
Unable to build on mint 17

### ISSUE THREAD

**Issue by debunge** [abeluck/stegdetect#1]
linux32 ./configure

works just fine, but 

linux32 make
cd . \
          && CONFIG_FILES= CONFIG_HEADERS=config.h \
             /bin/sh ./config.status
config.status: creating config.h
config.status: config.h is unchanged
/bin/sh: 1: Syntax error: ")" unexpected (expecting "then")
make: **\* [)].in]

What is the source of problem? Am I missing some dependency?

**Comment by arturo182** [comment]
+1 in 2016
