### ISSUE TITLE
Compiling failed on Debian Jessie

### ISSUE THREAD

**Issue by karstengit** [abeluck/stegdetect#6]
Making all in file
make[2]: Entering directory '/srv/test/steg/file'
gcc -DHAVE_CONFIG_H -I. -I. -I.   -DMAGIC='"/usr/local/share/magic"'  -g -O2 -c file.c
gcc -DHAVE_CONFIG_H -I. -I. -I.   -DMAGIC='"/usr/local/share/magic"'  -g -O2 -c apprentice.c
gcc -DHAVE_CONFIG_H -I. -I. -I.   -DMAGIC='"/usr/local/share/magic"'  -g -O2 -c fsmagic.c
gcc -DHAVE_CONFIG_H -I. -I. -I.   -DMAGIC='"/usr/local/share/magic"'  -g -O2 -c softmagic.c
gcc -DHAVE_CONFIG_H -I. -I. -I.   -DMAGIC='"/usr/local/share/magic"'  -g -O2 -c ascmagic.c
gcc -DHAVE_CONFIG_H -I. -I. -I.   -DMAGIC='"/usr/local/share/magic"'  -g -O2 -c compress.c
gcc -DHAVE_CONFIG_H -I. -I. -I.   -DMAGIC='"/usr/local/share/magic"'  -g -O2 -c is_tar.c
gcc -DHAVE_CONFIG_H -I. -I. -I.   -DMAGIC='"/usr/local/share/magic"'  -g -O2 -c readelf.c
gcc -DHAVE_CONFIG_H -I. -I. -I.   -DMAGIC='"/usr/local/share/magic"'  -g -O2 -c print.c
make[2]: *** No rule to make target 'Magdir/varied.out', needed by 'magic'.  Schluss.
make[2]: Leaving directory '/srv/test/steg/file'
Makefile:330: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/srv/test/steg'
Makefile:476: recipe for target 'all-recursive-am' failed
make: *** [all-recursive-am] Error 2

**Comment by themaddoctor** [comment]
touch file/Magdir/varied.out
make

Then you can get more problems later.

**Comment by abeluck** [comment]
It's building now on Debian 9.
